name: Build Native Go Tests

on:
  push:
    branches: [master]
    tags: ['v*']
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build-native:
    name: ${{ matrix.artifact }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            goos: windows
            goarch: amd64
            ext: .exe
            artifact: windows-amd64
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            ext: ""
            artifact: linux-amd64
          - os: macos-13
            goos: darwin
            goarch: amd64
            ext: ""
            artifact: darwin-amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
            ext: ""
            artifact: darwin-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - run: echo ok